config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'searches#search'
  get 'users/:id/favorites' => 'users#favorite'
  get '/about' => 'posts#about'
  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  root 'posts#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
 # バリデーション後usersアドレスに飛ばないように変更
  devise_scope :user do
    post 'users/sign_up', to: 'users/registrations#create'
    patch 'users/edit', to: 'users/registrations#update'
    put 'users/edit', to: 'users/registrations#update'
  end

  resources :users, only: [:show, :edit, :update]
  post '/conversions' => 'conversions#ocr'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # 仮想環境で使用するメールボックス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_like.html.erb
<% if user_signed_in? %>
<% if post.favorited_by?(current_user) %>
  いいね <%=link_to post_favorites_path(post.id), method: :delete, remote: true do %>
  <i class="fa fa-heart faa-pulse animated" aria-hidden="true" style="color: red;"></i>
  <%=post.favorites.count%>
  <% end %>
<% else %>
  いいね <%=link_to post_favorites_path(post.id), method: :post, remote: true do %>
  <i class="fa fa-heart faa-pulse animated" aria-hidden="true"></i>
  <%=post.favorites.count%>
<% end %>
<% end %>
<% else %>
  いいね
  <i class="fa fa-heart faa-pulse animated" aria-hidden="true" style="color: red;"></i>
  <%= post.favorites.count %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/like', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/like', locals: {post: @post}) %>");