config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'searches#search'
  get 'users/:id/favorites' => 'users#favorite'
  get '/about' => 'posts#about'
  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  root 'posts#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
 # バリデーション後usersアドレスに飛ばないように変更
  devise_scope :user do
    post 'users/sign_up', to: 'users/registrations#create'
    patch 'users/edit', to: 'users/registrations#update'
    put 'users/edit', to: 'users/registrations#update'
  end

  resources :users, only: [:show, :edit, :update]
  post '/conversions' => 'conversions#ocr'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # 仮想環境で使用するメールボックス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params)
    comment.user_id = current_user.id
    if comment.save
      @comments = post.comments
      @comments_count = @comments.count
      @comments_count_class = (@comments_count == 0)? "comments-none" : "comments-exist"
      render :index
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = Post.find(params[:post_id])
    if comment.destroy
      @comments = post.comments
      @comments_count = @comments.count
      @comments_count_class = (@comments_count == 0)? "comments-none" : "comments-exist"
      render :index
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |form| %>
  <div class="form-group">
    <%= form.text_area :content, class: 'form-control', style: "height: 150px;", placeholder: "コメントを入力してください" %>
  </div>
  <div class="form-group">
    <%= form.submit "コメントをする", class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
<div class="card border-warning my-sm-2 mb-sm-3 ">
  <h5 class="card-header border-warning">
    <% unless comment.id.nil? %>
    <p><%= attachment_image_tag comment.user, :image, :fill, 45, 45, class: "rounded-circle", fallback: "sample.jpg", size:'45x45'%>
    <%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %></p>
  </h5>
  <div class="card-body">
    <h5 class="card-title">コメント</h5>
    <p class="card-text"><%= comment.content %></p>
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: 'btn btn-warning float-right' %></p>
    <% end %>
  </div>
</div>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comments.reverse_order }) %>")
$("#comment_count").html("<i class=\"fas fa-comment-dots faa-float animated <%=@comments_count_class %>\"></i><%= @comments_count %>")
$("textarea").val('')