config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'searches#search'
  get 'users/:id/favorites' => 'users#favorite'
  get '/about' => 'posts#about'
  resources :posts do
  resources :comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  root 'posts#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
 # バリデーション後usersアドレスに飛ばないように変更
  devise_scope :user do
    post 'users/sign_up', to: 'users/registrations#create'
    patch 'users/edit', to: 'users/registrations#update'
    put 'users/edit', to: 'users/registrations#update'
  end

  resources :users, only: [:show, :edit, :update]
  post '/conversions' => 'conversions#ocr'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # 仮想環境で使用するメールボックス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Study</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.3.0/font-awesome-animation.min.css">
    <link href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

<body class="wrapper">
  <header>
    <nav class="navbar navbar-expand-xl navbar-dark rounded-bottom" style="background-color: #FF6699;">
      <% if user_signed_in? %>
        <I><%= link_to "Share Study", root_path, class: 'navbar-brand' %></I>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="Navber">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-item active nav-link fas fa-house-user' %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-item active nav-link fas fa-sign-out-alt' %>
              <%= link_to '新規投稿', new_post_path, class: 'nav-item active nav-link fas fa-pencil-alt' %>
              <%= link_to 'about', about_path, class: 'nav-item active nav-link fas fa-chess-rook' %>
            <span class="nav-item active nav-link ml-auto">
              ようこそ <%= current_user.name %>さん!
            </span>
              <div class="form-group mb-2">
                <%= form_with(url:search_path, method: :get, class: "nav-item form-control-plaintext form-inline ml-auto", data: {remote: false}) do %>
                <div class="col-sm-4 form-group mr-4">
                  <%= select_tag 'range' ,options_for_select([['--選択してください--', ''], ['ユーザー名', '1'], ['タグ', '2'],['投稿本文', '3']]), { autofocus: 'true', class: 'form-control'} %>
                </div>
                <div class="col-sm-4 form-group mr-4">
                  <%= text_field_tag (:word),"", {class: "form-control"} %>
                </div>
                <div class="col-sm-1 form-group">
                  <%= submit_tag "検索", class: 'btn btn-outline-light' %>
                </div>
              </div>
      <% end %>
            </div>
      <% else %>
        <I><%= link_to "Share Study", root_path, class: 'navbar-brand' %></I>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="Navber">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-item active nav-link fas fa-book' %>
              <%= link_to "ログイン", new_user_session_path, class: 'nav-item active nav-link fas fa-sign-in-alt' %>
              <%= link_to 'about', about_path, class: 'nav-item active nav-link fas fa-chess-rook' %>
            </div>
      <% end %>
    </nav>
  </header>
  <%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
<script>
  bsCustomFileInput.init();
  document.getElementById('inputFileReset').addEventListener('click', function() {
    var elem = document.getElementById('ocr_image');
    elem.value = '';
    elem.dispatchEvent(new Event('change'));
  });
</script>
</body>
<footer>
  <div class="text-center">
    <h6>2020 © Share Study All Rights Reserved </h6>
  </div>
</footer>
</html>

app/views/layouts/sub-layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Study</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.3.0/font-awesome-animation.min.css">
    <link href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

<body>
  <nav class="navbar navbar-expand-xl navbar-dark rounded-bottom" style="background-color: #FF6699;">
    <% if user_signed_in? %>
      <I><%= link_to "Share Study", root_path, class: 'navbar-brand' %></I>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="Navber">
        <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-item active nav-link fas fa-house-user' %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-item active nav-link fas fa-sign-out-alt' %>
        <%= link_to '新規投稿', new_post_path, class: 'nav-item active nav-link fas fa-pencil-alt' %>
        <%= link_to 'about', about_path, class: 'nav-item active nav-link fas fa-chess-rook' %>
      <span class="nav-item active nav-link ml-auto">
        ようこそ <%= current_user.name %>さん!
      </span>
        <div class="form-group mb-2">
          <%= form_with(url:search_path, method: :get, class: "nav-item form-control-plaintext form-inline ml-auto", data: {remote: false}) do %>
            <div class="col-sm-4 form-group mr-4">
              <%= select_tag 'range' ,options_for_select([['--選択してください--', ''], ['ユーザー名', '1'], ['タグ', '2'],['投稿本文', '3']]), { autofocus: 'true', class: 'form-control'} %>
            </div>
            <div class="col-sm-4 form-group mr-4">
              <%= text_field_tag (:word),"", {class: "form-control"} %>
            </div>
            <div class="col-sm-1 form-group">
              <%= submit_tag "検索", class: 'btn btn-outline-light' %>
            </div>
        </div>
    <% end %>
      </div>
      <% else %>
    <I><%= link_to "Share Study", root_path, class: 'navbar-brand' %></I>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="Navber">
      <%= link_to 'about', about_path, class: 'nav-item active nav-link fas fa-chess-rook' %>
    </div>
    <% end %>
  </nav>
<%= yield %>
</body>
<footer>
  <div class="text-center">
    <h6>2020 © Share Study All Rights Reserved </h6>
  </div>
</footer>
</html>